### ISSUE TITLE
Module 2 - IAM Role to Stream log to Kinesis FireHose and System Manager 

### ISSUE THREAD

**Issue by phonghuule** [saltysoup/Building-a-real-time-data-platform-on-AWS#2]
Step 2 - Publishing Clickstream Logs via Kinesis Agent
Missing step to create IAM Role with permission to PutRecordBatch on Firehose Stream.
Attach policy AmazonEC2RoleForSSM to the Role, so that user can see the instance in System Manager
Attach this role to the EC2 instance

**Comment by saltysoup** [comment]
I've attached an IAM role with admin permissions for EC2 to make it easy; but you're right least privilege should be the way.

I'll see if i can narrow down the permissions if i have time

**Comment by saltysoup** [comment]
Updated Wordpress EC2 IAM role with more restrictive permissions
