### ISSUE TITLE
Module 1 - Should tell users to use their resource ARN

### ISSUE THREAD

**Issue by phonghuule** [saltysoup/Building-a-real-time-data-platform-on-AWS#3]
**Monitoring Web Requests through AWS WAF -> Storing, Indexing and Searching Data with an Amazon Elasticsearch cluster ->Step 9**
Users are told to enter their IP Address. Tell them to enter their own ElasticSearch ARN. This is to avoid them using "Resource": "arn:aws:es:ap-southeast-1:708252083442:domain/realtime/*" in the Access Policy

**Comment by saltysoup** [comment]
updated example output of resource with placeholder values.

| Users are told to enter their IP Address
| If users enter their IP address, it automatically generates the template so they shouldnt be replacing what they have with my example with IP address and resource ARN
